label_map={
    "background": 0,
    "hat": 1,
    "hair": 2,
    "sunglasses": 3,
    "upper_clothes": 4,
    "skirt": 5,
    "pants": 6,
    "dress": 7,
    "belt": 8,
    "left_shoe": 9,
    "right_shoe": 10,
    "head": 11,
    "left_leg": 12,
    "right_leg": 13,
    "left_arm": 14,
    "right_arm": 15,
    "bag": 16,
    "scarf": 17,
}

LIP_map = {
    'background' : 0,
    'hat' : 1,
    'hair' : 2, 
    'glove' : 3, 
    'sunglasses': 4, 
    'upper_clothes' : 5, 
    'dress' : 6, 
    'coat': 7, 
    'socks': 8, 
    'pants': 9, 
    'jumpsuits' : 10, 
    'scarf': 11, 
    'skirt': 12, 
    'face' : 13, 
    'left_arm' : 14, 
    'right_arm': 15, 
    'left_leg': 16, 
    'right_leg':17, 
    'left_shoe': 18, 
    'right_shoe': 19.
}